### ISSUE TITLE
Arke v0.1.9 have error

### ISSUE THREAD

**Issue by huuhait** [rubykube/arke#67]
i'm using arke v0.1.9

At first, every order is made very well

but after only a few minutes it reported an error: FATAL -- : Code: 422 Message: Unprocessable Entity
![image](https://user-images.githubusercontent.com/40519768/54486273-90152d00-48b8-11e9-997a-32b8c7970447.png)

**Comment by colombo-77** [comment]
Hi, did you find a solution to this? I am trying to fix the same error ...

![image](https://user-images.githubusercontent.com/62880703/99729896-deca8f80-2abb-11eb-903d-51b41bdf1e5e.png)
