### ISSUE TITLE
Use correct API KEY+secret but getting authz error

### ISSUE THREAD

**Issue by bitbd83** [rubykube/arke#70]
always getting this error.

 [2019-06-10T22:16:35.184080 #2294] FATAL -- : {"errors"=>["authz.invalid_session"]}

**Comment by bitbd83** [comment]
Last update
------------------
F, [2019-06-12T21:42:30.639442 #1] FATAL -- :   
F, [2019-06-12T21:42:30.640499 #1] FATAL -- : NoMethodError (undefined method `data' for nil:NilClass):
F, [2019-06-12T21:42:30.640538 #1] FATAL -- :   
F, [2019-06-12T21:42:30.640559 #1] FATAL -- : app/services/api_keys_verifier.rb:13:in `verify_hmac_payload?'

**Comment by webdev0828** [comment]
I also have the same issue.

**Comment by bitbd83** [comment]
I have resolved and mastering with this stuff.

**Comment by ianeinser** [comment]
> I have resolved and mastering with this stuff.

and how did you resolve it? @bitbd83

**Comment by webpolis** [comment]
what an ass** @bitbd83 .. share your findings
